### PR TITLE
GUI Major Rebuild

### PR DESCRIPTION
**Pull request by mananpal1997**
pic1
pic2

I've added scroll-bar support to main window and BACKSPACE key is used to go back to home main window.

### CODE REVIEW

**Comment by ashwini0529** [comment]
Hey, @mananpal1997 Great Job.
But it gives out an error when you just type in username, and leave repository field empty.

```
Traceback (most recent call last):
  File "git-gui.py", line 68, in submit
    self.switch_view()
  File "git-gui.py", line 107, in switch_view
    issues = issue_tag.find('span', {'class': 'counter'}).text
AttributeError: 'NoneType' object has no attribute 'find'
```

Can add an exception handler here and create a pull request again?

**Comment by mananpal1997** [comment]
Its fixed, @ashwini0529

**Comment by ashwini0529** [comment]
Great work @mananpal1997 .
Still the UI is not up to the mark. We need to design a better User Interface and add more attributes.
Let's work upon it.
I'll work on adding more attribute and you can work on designing it.
Is that Okay?

**Comment by mananpal1997** [comment]
@ashwini0529 Yeah, sure. First thing we need is to make it threaded. So that components are loaded with the main app without getting stuck/hang. Plus, I've started working on folder/file navigation inside repository 👍

**Comment by mananpal1997** [comment]
@ashwini0529 you there?

**Comment by ashwini0529** [comment]
Yeah. I was busy in something. 
Let's plan out the basic workflow of the GUI application.

**Pull request merged**
