### PR TITLE
GUI-Architecture with notifications support using login credentials

### PR DESCRIPTION
**Pull request by mananpal1997**
Fix for [#34](https://github.com/ashwini0529/git-repo/issues/34)
How does it look?

### CODE REVIEW

**Comment by ashwini0529** [comment]
We can use Github OAuth for login.

**Comment by mananpal1997** [comment]
I'll give it a try

**Comment by mananpal1997** [comment]
@ashwini0529 can you help me with OAuth? I'm having some problem with getting it to work.

**Comment by ashwini0529** [comment]
Yeah sure! Tell  me where are you stuck? @mananpal1997

**Comment by mananpal1997** [comment]
Do we keep oauth credentials for the app public?
Or users have to configure themselves for their systems?

**Comment by ashwini0529** [comment]
We can keep the first screen as login screen. And once the user logs in successfully, we can show stuff.

**Comment by ashwini0529** [comment]
@mananpal1997 why did you close this pr?

**Pull request closed without merging**
